// ESLint flat config for this Expo project.
// Base rules come from eslint-config-expo (Expo SDK 57); project ignores below.
import { defineConfig } from "eslint/config";
import expoConfig from "eslint-config-expo/flat.js";

export default defineConfig([
  expoConfig,
  {
    // Build output plus Borel-managed/generated sources. The listed files are
    // regenerated by Borel (see AGENTS.md conventions), and the borel-*.js
    // bridges are vendor code, so linting them only reports noise that cannot
    // be fixed here. Implementation in the db/ and auth/ subfolders is still
    // linted.
    ignores: [
      "dist/*",
      ".expo/*",
      "src/index.tsx",
      "src/lib/core/db.ts",
      "src/lib/core/auth.tsx",
      "src/lib/core/legal.tsx",
      "src/lib/ui/fonts.tsx",
      "borel-store.js",
      "borel-systemui.js",
    ],
  },
]);
